<script lang="ts">
    import * as Dialog from "$lib/components/ui/dialog/index.js";
    import * as Drawer from "$lib/components/ui/drawer/index.js";
    import Button from "$lib/components/ui/button/button.svelte";
    import { cn } from "$lib/utils";
    import { confidenceLabels, confidenceBgColors } from "$lib/confidence";
    import { browser } from "$app/environment";
    import type { Snippet } from "svelte";

    /**
     * Responsive "Mark done" component.
     *
     * The trick: we detect screen width with matchMedia and render
     * either a Dialog (desktop) or Drawer (mobile). Both wrap the
     * same content — a confidence level picker.
     *
     * Why matchMedia instead of CSS?
     * Because Dialog and Drawer are completely different component
     * trees (different portals, different animations, different a11y).
     * You can't toggle between them with CSS alone — you need to
     * conditionally render the right one in JS.
     *
     * generated by AI, claude
     */

    interface MarkDoneTopic {
        key?: string;
        title: string;
        currentConfidence: number;
    }

    interface Props {
        topicTitle?: string;
        currentConfidence?: number;
        topics?: MarkDoneTopic[];
        onSelect: (
            confidence: number,
            topic: MarkDoneTopic,
            index: number,
        ) => void | Promise<unknown>;
        children: Snippet;
    }

    let {
        topicTitle = "",
        currentConfidence = 0,
        topics = [],
        onSelect,
        children,
    }: Props = $props();

    // Controls whether the dialog/drawer is open.
    // Both Dialog.Root and Drawer.Root accept `open` as a bindable prop.
    let open = $state(false);

    const incomingTargets = $derived(
        topics.length > 0 ? topics : [{ title: topicTitle, currentConfidence }],
    );
    let reviewTargets: MarkDoneTopic[] = $state([]);
    const targets = $derived(open ? reviewTargets : incomingTargets);
    const isGroup = $derived(targets.length > 1);

    // -- Responsive detection --
    // matchMedia gives us a live boolean that updates on resize.
    // We wire it into Svelte's reactivity with $state + $effect.
    let isDesktop = $state(true);

    $effect(() => {
        if (!browser) return;

        const mq = window.matchMedia("(min-width: 768px)");
        isDesktop = mq.matches;

        const handler = (e: MediaQueryListEvent) => {
            isDesktop = e.matches;
        };
        mq.addEventListener("change", handler);

        return () => mq.removeEventListener("change", handler);
    });

    let isSaving = $state(false);
    let activeIndex = $state(0);
    let selectedConfidences: number[] = $state([]);
    let topicScroller: HTMLDivElement | null = $state(null);
    let wasOpen = $state(false);

    $effect(() => {
        if (open && !wasOpen) {
            reviewTargets = incomingTargets.map((topic) => ({ ...topic }));
            selectedConfidences = incomingTargets.map(
                (topic) => topic.currentConfidence,
            );
            activeIndex = 0;
        }

        if (!open && wasOpen) {
            activeIndex = 0;
            selectedConfidences = [];
            reviewTargets = [];
        }

        wasOpen = open;
    });

    async function handleSelect(level: number) {
        if (isSaving) return;

        isSaving = true;
        try {
            const topic = targets[0];
            if (!topic) return;

            await onSelect(level, topic, 0);
            open = false;
        } finally {
            isSaving = false;
        }
    }

    function setSelectedConfidence(index: number, level: number) {
        const next = [...selectedConfidences];
        next[index] = level;
        selectedConfidences = next;
    }

    function scrollToTopic(index: number) {
        activeIndex = Math.max(0, Math.min(index, targets.length - 1));
        requestAnimationFrame(() => {
            topicScroller?.children[activeIndex]?.scrollIntoView({
                behavior: "smooth",
                block: "nearest",
                inline: "start",
            });
        });
    }

    function handleTopicScroll() {
        if (!topicScroller) return;

        let nextIndex = 0;
        let nextDistance = Infinity;
        Array.from(topicScroller.children).forEach((child, index) => {
            const distance = Math.abs(
                (child as HTMLElement).offsetLeft - topicScroller!.scrollLeft,
            );
            if (distance < nextDistance) {
                nextIndex = index;
                nextDistance = distance;
            }
        });
        activeIndex = nextIndex;
    }

    function handleGroupSelect(index: number, level: number) {
        const topic = targets[index];
        if (!topic || isSaving) return;

        setSelectedConfidence(index, level);
        if (index < targets.length - 1) {
            scrollToTopic(index + 1);
        }
    }

    async function handleGroupSave() {
        if (isSaving) return;

        isSaving = true;
        try {
            await Promise.all(
                targets.map((topic, index) =>
                    onSelect(
                        selectedConfidences[index] ?? topic.currentConfidence,
                        topic,
                        index,
                    ),
                ),
            );
            open = false;
        } finally {
            isSaving = false;
        }
    }
</script>

<!--
    The {#snippet} block defines reusable markup within a single component.
    We define the confidence picker once, then render it inside either
    the Dialog or Drawer body. This is Svelte 5's replacement for slots
    when you need to reuse content in multiple places within the same file.
-->
{#snippet confidencePicker()}
    <div class="flex min-w-0 flex-col gap-3 p-4 md:p-0">
        {#if isGroup}
            <div
                class="flex min-w-0 items-center gap-2 text-xs text-muted-foreground"
            >
                <span class="shrink-0">
                    Topic {activeIndex + 1} of {targets.length}
                </span>
                <div class="ml-auto flex shrink-0 gap-1 pr-1">
                    {#each targets as topic, i (topic.key ?? `${topic.title}-${i}`)}
                        <button
                            class={cn(
                                "size-2 rounded-full transition-colors",
                                i === activeIndex
                                    ? "bg-foreground"
                                    : "bg-muted-foreground/35 hover:bg-muted-foreground/60",
                            )}
                            aria-label="Go to topic {i + 1}"
                            onclick={() => scrollToTopic(i)}
                        ></button>
                    {/each}
                </div>
            </div>

            <div
                bind:this={topicScroller}
                class="flex min-w-0 max-w-full snap-x snap-mandatory gap-3 overflow-x-auto scroll-smooth pb-1"
                onscroll={handleTopicScroll}
            >
                {#each targets as topic, index (topic.key ?? `${topic.title}-${index}`)}
                    <div
                        class="flex w-full shrink-0 snap-start flex-col gap-3 rounded-md border border-dashed p-3"
                    >
                        <p class="text-sm text-muted-foreground">
                            How confident are you about <span
                                class="font-medium text-foreground wrap-break-word"
                                title={topic.title}>{topic.title}</span
                            >?
                        </p>
                        <div class="flex flex-col gap-1.5">
                            {#each confidenceLabels as label, i (label)}
                                {@const level = i + 1}
                                <Button
                                    variant="outline"
                                    class={cn(
                                        "h-auto w-full justify-start gap-3 px-3 py-2.5",
                                        level ===
                                            (selectedConfidences[index] ??
                                                topic.currentConfidence) &&
                                            "border-primary bg-primary/5",
                                    )}
                                    disabled={isSaving}
                                    onclick={() =>
                                        handleGroupSelect(index, level)}
                                >
                                    <div
                                        class={cn(
                                            "size-3 rounded-md shrink-0",
                                            confidenceBgColors[i],
                                        )}
                                    ></div>
                                    <span>{label}</span>
                                </Button>
                            {/each}
                        </div>
                    </div>
                {/each}
            </div>

            <div class="flex min-w-0 items-center gap-2">
                <Button
                    variant="outline"
                    size="xs"
                    disabled={activeIndex === 0 || isSaving}
                    onclick={() => scrollToTopic(activeIndex - 1)}
                >
                    Previous
                </Button>
                <Button
                    variant="outline"
                    size="xs"
                    disabled={activeIndex >= targets.length - 1 || isSaving}
                    onclick={() => scrollToTopic(activeIndex + 1)}
                >
                    Next
                </Button>
                <Button
                    variant="default"
                    size="xs"
                    class="ml-auto"
                    disabled={isSaving}
                    onclick={handleGroupSave}
                >
                    {isSaving ? "Saving..." : "Save"}
                </Button>
            </div>
        {:else}
            <p class="text-sm text-muted-foreground">
                How confident are you about <span
                    class="font-medium text-foreground break-words"
                    title={targets[0]?.title}>{targets[0]?.title}</span
                >?
            </p>
            <div class="flex flex-col gap-1.5">
                {#each confidenceLabels as label, i (label)}
                    {@const level = i + 1}
                    <Button
                        variant="outline"
                        class={cn(
                            "h-auto w-full justify-start gap-3 px-3 py-2.5",
                            level === targets[0]?.currentConfidence &&
                                "border-primary bg-primary/5",
                        )}
                        disabled={isSaving}
                        onclick={() => handleSelect(level)}
                    >
                        <div
                            class={cn(
                                "size-3 rounded-md shrink-0",
                                confidenceBgColors[i],
                            )}
                        ></div>
                        <span>{label}</span>
                    </Button>
                {/each}
            </div>
        {/if}
    </div>
{/snippet}

<!--
    Now the responsive switch.
    isDesktop = true  → render Dialog (centered modal)
    isDesktop = false → render Drawer (slides up from bottom)

    Both use the same `open` state and render the same `confidencePicker` snippet.
-->
{#if isDesktop}
    <Dialog.Root bind:open>
        <Dialog.Trigger>
            <!--
                @render children() renders whatever the parent passes
                as the component's children. This is the trigger button.
            -->
            {@render children()}
        </Dialog.Trigger>
        <Dialog.Content
            class={cn(
                "overflow-hidden",
                isGroup ? "sm:max-w-lg" : "sm:max-w-sm",
            )}
        >
            <Dialog.Header>
                <Dialog.Title>Mark as reviewed</Dialog.Title>
                <Dialog.Description>
                    {#if isGroup}
                        Review each topic in this group.
                    {:else}
                        Update your confidence level after reviewing this topic.
                    {/if}
                </Dialog.Description>
            </Dialog.Header>
            {@render confidencePicker()}
        </Dialog.Content>
    </Dialog.Root>
{:else}
    <Drawer.Root bind:open>
        <Drawer.Trigger>
            {@render children()}
        </Drawer.Trigger>
        <Drawer.Content>
            <Drawer.Header class="text-left">
                <Drawer.Title>Mark as reviewed</Drawer.Title>
                <Drawer.Description>
                    {#if isGroup}
                        Review each topic in this group.
                    {:else}
                        Update your confidence level after reviewing this topic.
                    {/if}
                </Drawer.Description>
            </Drawer.Header>
            {@render confidencePicker()}
            <Drawer.Footer>
                <Drawer.Close>Cancel</Drawer.Close>
            </Drawer.Footer>
        </Drawer.Content>
    </Drawer.Root>
{/if}
