<script lang="ts">
    import * as Dialog from "$lib/components/ui/dialog/index.js";
    import * as Drawer from "$lib/components/ui/drawer/index.js";
    import { cn } from "$lib/utils";
    import { confidenceLabels, confidenceBgColors } from "$lib/confidence";
    import { browser } from "$app/environment";
    import type { Snippet } from "svelte";

    /**
     * Responsive "Mark done" component.
     *
     * The trick: we detect screen width with matchMedia and render
     * either a Dialog (desktop) or Drawer (mobile). Both wrap the
     * same content — a confidence level picker.
     *
     * Why matchMedia instead of CSS?
     * Because Dialog and Drawer are completely different component
     * trees (different portals, different animations, different a11y).
     * You can't toggle between them with CSS alone — you need to
     * conditionally render the right one in JS.
     *
     * generated by AI, claude
     */

    interface Props {
        topicTitle: string;
        currentConfidence: number;
        onSelect: (confidence: number) => void;
        children: Snippet;
    }

    let { topicTitle, currentConfidence, onSelect, children }: Props = $props();

    // -- Responsive detection --
    // matchMedia gives us a live boolean that updates on resize.
    // We wire it into Svelte's reactivity with $state + $effect.
    let isDesktop = $state(true);

    $effect(() => {
        if (!browser) return;

        const mq = window.matchMedia("(min-width: 768px)");
        isDesktop = mq.matches;

        const handler = (e: MediaQueryListEvent) => {
            isDesktop = e.matches;
        };
        mq.addEventListener("change", handler);

        return () => mq.removeEventListener("change", handler);
    });

    // Controls whether the dialog/drawer is open.
    // Both Dialog.Root and Drawer.Root accept `open` as a bindable prop.
    let open = $state(false);

    function handleSelect(level: number) {
        onSelect(level);
        open = false;
    }
</script>

<!--
    The {#snippet} block defines reusable markup within a single component.
    We define the confidence picker once, then render it inside either
    the Dialog or Drawer body. This is Svelte 5's replacement for slots
    when you need to reuse content in multiple places within the same file.
-->
{#snippet confidencePicker()}
    <div class="flex flex-col gap-3 p-4 md:p-0">
        <p class="text-sm text-muted-foreground">
            How confident are you about <span
                class="font-medium text-foreground">{topicTitle}</span
            >?
        </p>
        <div class="flex flex-col gap-1.5">
            {#each confidenceLabels as label, i (label)}
                {@const level = i + 1}
                <button
                    class={cn(
                        "flex items-center gap-3 rounded-md border px-3 py-2.5 text-sm transition-colors hover:bg-accent",
                        level === currentConfidence &&
                            "border-primary bg-primary/5",
                    )}
                    onclick={() => handleSelect(level)}
                >
                    <div
                        class={cn(
                            "size-3 rounded-sm shrink-0",
                            confidenceBgColors[i],
                        )}
                    ></div>
                    <span>{label}</span>
                </button>
            {/each}
        </div>
    </div>
{/snippet}

<!--
    Now the responsive switch.
    isDesktop = true  → render Dialog (centered modal)
    isDesktop = false → render Drawer (slides up from bottom)

    Both use the same `open` state and render the same `confidencePicker` snippet.
-->
{#if isDesktop}
    <Dialog.Root bind:open>
        <Dialog.Trigger>
            <!--
                @render children() renders whatever the parent passes
                as the component's children. This is the trigger button.
            -->
            {@render children()}
        </Dialog.Trigger>
        <Dialog.Content class="sm:max-w-sm">
            <Dialog.Header>
                <Dialog.Title>Mark as reviewed</Dialog.Title>
                <Dialog.Description>
                    Update your confidence level after reviewing this topic.
                </Dialog.Description>
            </Dialog.Header>
            {@render confidencePicker()}
        </Dialog.Content>
    </Dialog.Root>
{:else}
    <Drawer.Root bind:open>
        <Drawer.Trigger>
            {@render children()}
        </Drawer.Trigger>
        <Drawer.Content>
            <Drawer.Header class="text-left">
                <Drawer.Title>Mark as reviewed</Drawer.Title>
                <Drawer.Description>
                    Update your confidence level after reviewing this topic.
                </Drawer.Description>
            </Drawer.Header>
            {@render confidencePicker()}
            <Drawer.Footer>
                <Drawer.Close>Cancel</Drawer.Close>
            </Drawer.Footer>
        </Drawer.Content>
    </Drawer.Root>
{/if}
